[package]
name = "rust-player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# audio
rodio = {version = "0.17.1",features = ["symphonia-all"]}
symphonia = { version = "0.5.3", features = ["all-codecs"] }
tempfile = "3.6.0"
tokio = { version = "1", features = ["full"] }
reqwest = {version = "0.11.18", features = ["blocking"] }
anyhow = "1.0"
thiserror = "1.0"
stream-download = "0.3.0"
tracing = "0.1"
tracing-subscriber = {version = "0.3", features=["env-filter"]}
rand = "0.8.5"
