[package]
name = "rust-player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# audio
rodio = {version = "0.17.1",features = ["symphonia-aac"]}
tempfile = "3.6.0"
symphonia = "0.5.3"
tokio = { version = "1", features = ["full"] }
bytes = "1.4.0"
reqwest = {version = "0.11.18", features = ["blocking"] }
anyhow = "1.0"
